### PR TITLE
Create Median.java

### PR DESCRIPTION
**Pull request by osama-hamad**

### CODE REVIEW

**Review by prime-hacker — COMMENTED** [review]
I think we're not supposed to make separate classes. You develop your own method inside of Main class.

**Review by MonaAhmed810 — COMMENTED** [review]
please pull the master code and write your code in Function in the Main Class

**Comment by osama-hamad** [comment]
I wrote my function into main class please review my request

**Comment by MonaAhmed810** [comment]
please resolve the conflicts

**Comment by MonaAhmed810** [comment]
please pull last version for master.
add your function.
don't sort directly the original array but take copy.

**Pull request closed without merging**
